services:
  - type: web
    name: haomeili-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false